services:
  frontend:
    image: ghcr.io/rorycondict/evp-website/frontend:latest
    container_name: evp-frontend
    depends_on:
      - backend
    ports:
      - "16017:16017"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # prod specific
    restart: unless-stopped

  backend:
    image: ghcr.io/rorycondict/evp-website/backend:latest
    container_name: evp-backend
    # prod specific
    command: uv run uvicorn main:app
    env_file:
      - ./.env
    restart: unless-stopped