server {
    listen 16017;
    server_name www.edinburghventurepoint.com;

    root /usr/share/nginx/html;
    index index.html;

    # redirects
    location /investing {
        return 301 /contact#scout-programme;
    }

    location /meet-the-team {
        return 301 /about#meet-the-team;
    }

    location /partners {
        return 301 /contact#network;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;   
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}