limit_req_zone $binary_remote_addr zone=newsletter:10m rate=2r/m;
limit_req_zone $binary_remote_addr zone=contact:10m rate=1r/m;

server {
    listen 16017;
    root /usr/share/nginx/html;

    limit_req_status 429;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /api/newsletter-subscribe {
        limit_req zone=newsletter burst=3 nodelay;

        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /api/contact-submit {
        limit_req zone=contact burst=3 nodelay;

        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # redirects
    location = /investing {
        return 301 /contact#scout-programme;
    }

    location = /meet-the-team {
        return 301 /about#meet-the-team;
    }

    location = /partners {
        return 301 /contact#network;
    }
}