/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface ContactForm {
  /**
     * @minLength 1
     * @maxLength 100
     */
  first_name: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  last_name: string;
  /** @maxLength 254 */
  email: string;
  /**
     * @minLength 1
     * @maxLength 10000
     */
  message: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface NewsletterForm {
  /**
     * @minLength 1
     * @maxLength 100
     */
  first_name: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  last_name: string;
  /** @maxLength 254 */
  email: string;
}

/**
 * @summary Submit Contact Form
 */
export const submitContactForm = (
    contactForm: ContactForm, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.post(
      `/api/contact-submit`,
      contactForm,options
    );
  }




export const getSubmitContactFormMutationKey = () => ['submitContactForm'] as const;

export const getSubmitContactFormMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitContactForm>>, TError,SubmitContactFormMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof submitContactForm>>, TError,SubmitContactFormMutationVariables, TContext> => {

const mutationKey = getSubmitContactFormMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitContactForm>>, SubmitContactFormMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  submitContactForm(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitContactFormMutationResult = NonNullable<Awaited<ReturnType<typeof submitContactForm>>>
    export type SubmitContactFormMutationBody = ContactForm
    export type SubmitContactFormMutationError = AxiosError<HTTPValidationError>
    export type SubmitContactFormMutationVariables = {data: ContactForm}

    /**
 * @summary Submit Contact Form
 */
export const useSubmitContactForm = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitContactForm>>, TError,SubmitContactFormMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitContactForm>>,
        TError,
        SubmitContactFormMutationVariables,
        TContext
      > => {
      return useMutation(getSubmitContactFormMutationOptions(options), queryClient);
    }

/**
 * @summary Subscribe To Newsletter
 */
export const subscribeToNewsletter = (
    newsletterForm: NewsletterForm, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {


    return axios.default.post(
      `/api/newsletter-subscribe`,
      newsletterForm,options
    );
  }




export const getSubscribeToNewsletterMutationKey = () => ['subscribeToNewsletter'] as const;

export const getSubscribeToNewsletterMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeToNewsletter>>, TError,SubscribeToNewsletterMutationVariables, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeToNewsletter>>, TError,SubscribeToNewsletterMutationVariables, TContext> => {

const mutationKey = getSubscribeToNewsletterMutationKey();
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeToNewsletter>>, SubscribeToNewsletterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  subscribeToNewsletter(data,axiosOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeToNewsletterMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeToNewsletter>>>
    export type SubscribeToNewsletterMutationBody = NewsletterForm
    export type SubscribeToNewsletterMutationError = AxiosError<HTTPValidationError>
    export type SubscribeToNewsletterMutationVariables = {data: NewsletterForm}

    /**
 * @summary Subscribe To Newsletter
 */
export const useSubscribeToNewsletter = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeToNewsletter>>, TError,SubscribeToNewsletterMutationVariables, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof subscribeToNewsletter>>,
        TError,
        SubscribeToNewsletterMutationVariables,
        TContext
      > => {
      return useMutation(getSubscribeToNewsletterMutationOptions(options), queryClient);
    }
