/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

export interface ContactForm {
  first_name: string;
  last_name: string;
  email: string;
  message: string;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface NewsletterForm {
  first_name: string;
  last_name: string;
  email: string;
}

export type submitContactFormApiContactSubmitPostResponse204 = {
  data: void
  status: 204
}

export type submitContactFormApiContactSubmitPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type submitContactFormApiContactSubmitPostResponseSuccess = (submitContactFormApiContactSubmitPostResponse204) & {
  headers: Headers;
};
export type submitContactFormApiContactSubmitPostResponseError = (submitContactFormApiContactSubmitPostResponse422) & {
  headers: Headers;
};

export type submitContactFormApiContactSubmitPostResponse = (submitContactFormApiContactSubmitPostResponseSuccess | submitContactFormApiContactSubmitPostResponseError)

export const getSubmitContactFormApiContactSubmitPostUrl = () => {




  return `/api/contact-submit`
}

/**
 * @summary Submit Contact Form
 */
export const submitContactFormApiContactSubmitPost = async (contactForm: ContactForm, options?: RequestInit): Promise<submitContactFormApiContactSubmitPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSubmitContactFormApiContactSubmitPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(contactForm)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: submitContactFormApiContactSubmitPostResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as submitContactFormApiContactSubmitPostResponse
}





export const getSubmitContactFormApiContactSubmitPostMutationKey = () => ['submitContactFormApiContactSubmitPost'] as const;

export const getSubmitContactFormApiContactSubmitPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitContactFormApiContactSubmitPost>>, TError,SubmitContactFormApiContactSubmitPostMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof submitContactFormApiContactSubmitPost>>, TError,SubmitContactFormApiContactSubmitPostMutationVariables, TContext> => {

const mutationKey = getSubmitContactFormApiContactSubmitPostMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitContactFormApiContactSubmitPost>>, SubmitContactFormApiContactSubmitPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  submitContactFormApiContactSubmitPost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitContactFormApiContactSubmitPostMutationResult = NonNullable<Awaited<ReturnType<typeof submitContactFormApiContactSubmitPost>>>
    export type SubmitContactFormApiContactSubmitPostMutationBody = ContactForm
    export type SubmitContactFormApiContactSubmitPostMutationError = HTTPValidationError
    export type SubmitContactFormApiContactSubmitPostMutationVariables = {data: ContactForm}

    /**
 * @summary Submit Contact Form
 */
export const useSubmitContactFormApiContactSubmitPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitContactFormApiContactSubmitPost>>, TError,SubmitContactFormApiContactSubmitPostMutationVariables, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof submitContactFormApiContactSubmitPost>>,
        TError,
        SubmitContactFormApiContactSubmitPostMutationVariables,
        TContext
      > => {
      return useMutation(getSubmitContactFormApiContactSubmitPostMutationOptions(options));
    }

export type subscribeToNewsletterApiNewsletterSubscribePostResponse204 = {
  data: void
  status: 204
}

export type subscribeToNewsletterApiNewsletterSubscribePostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type subscribeToNewsletterApiNewsletterSubscribePostResponseSuccess = (subscribeToNewsletterApiNewsletterSubscribePostResponse204) & {
  headers: Headers;
};
export type subscribeToNewsletterApiNewsletterSubscribePostResponseError = (subscribeToNewsletterApiNewsletterSubscribePostResponse422) & {
  headers: Headers;
};

export type subscribeToNewsletterApiNewsletterSubscribePostResponse = (subscribeToNewsletterApiNewsletterSubscribePostResponseSuccess | subscribeToNewsletterApiNewsletterSubscribePostResponseError)

export const getSubscribeToNewsletterApiNewsletterSubscribePostUrl = () => {




  return `/api/newsletter-subscribe`
}

/**
 * @summary Subscribe To Newsletter
 */
export const subscribeToNewsletterApiNewsletterSubscribePost = async (newsletterForm: NewsletterForm, options?: RequestInit): Promise<subscribeToNewsletterApiNewsletterSubscribePostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getSubscribeToNewsletterApiNewsletterSubscribePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(newsletterForm)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: subscribeToNewsletterApiNewsletterSubscribePostResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as subscribeToNewsletterApiNewsletterSubscribePostResponse
}





export const getSubscribeToNewsletterApiNewsletterSubscribePostMutationKey = () => ['subscribeToNewsletterApiNewsletterSubscribePost'] as const;

export const getSubscribeToNewsletterApiNewsletterSubscribePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeToNewsletterApiNewsletterSubscribePost>>, TError,SubscribeToNewsletterApiNewsletterSubscribePostMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof subscribeToNewsletterApiNewsletterSubscribePost>>, TError,SubscribeToNewsletterApiNewsletterSubscribePostMutationVariables, TContext> => {

const mutationKey = getSubscribeToNewsletterApiNewsletterSubscribePostMutationKey();
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof subscribeToNewsletterApiNewsletterSubscribePost>>, SubscribeToNewsletterApiNewsletterSubscribePostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  subscribeToNewsletterApiNewsletterSubscribePost(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubscribeToNewsletterApiNewsletterSubscribePostMutationResult = NonNullable<Awaited<ReturnType<typeof subscribeToNewsletterApiNewsletterSubscribePost>>>
    export type SubscribeToNewsletterApiNewsletterSubscribePostMutationBody = NewsletterForm
    export type SubscribeToNewsletterApiNewsletterSubscribePostMutationError = HTTPValidationError
    export type SubscribeToNewsletterApiNewsletterSubscribePostMutationVariables = {data: NewsletterForm}

    /**
 * @summary Subscribe To Newsletter
 */
export const useSubscribeToNewsletterApiNewsletterSubscribePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof subscribeToNewsletterApiNewsletterSubscribePost>>, TError,SubscribeToNewsletterApiNewsletterSubscribePostMutationVariables, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof subscribeToNewsletterApiNewsletterSubscribePost>>,
        TError,
        SubscribeToNewsletterApiNewsletterSubscribePostMutationVariables,
        TContext
      > => {
      return useMutation(getSubscribeToNewsletterApiNewsletterSubscribePostMutationOptions(options));
    }
